move to pyproject.toml
pastas/metran pull request #19
Opened 2023-09-12 07:49 UTC by martinvonk

I'm getting issues installing Metran (using the old setup.py method). So I've created a pyproject.toml just like Pastas.

2023-09-28 14:20 UTC, dbrakenhoff commented on .readthedocs.yml
> +      extra_requirements:
rmeove

2023-09-28 14:21 UTC, dbrakenhoff commented on pyproject.toml
> +[project.optional-dependencies]
add ci section

2023-09-28 14:21 UTC, dbrakenhoff commented on .github/workflows/ci.yml
>            pip install codecov
move these to ci under [project.optional_dependencies]

2023-09-28 14:22 UTC, dbrakenhoff requested changes
see comments

2023-09-29 13:56 UTC, dbrakenhoff commented on pyproject.toml
> +ci = ["metran[linting,pytsting,coveraging]"]
pytest-dependency should formally be part of the pytesting category

2023-09-29 13:57 UTC, martinvonk commented on pyproject.toml
> +ci = ["metran[linting,pytsting,coveraging]"]
whoopsi

2023-09-29 13:58 UTC, merged